package es.uniovi.pulso.colmena.model.enumeration;

public enum IndicatorType {
	USER_DATA, USER_AVERAGE, USER_AVERAGE_MORE, USER_AVERAGE_LESS, USER_LEVEL, USER_LEVEL_INITIAL, USER_LEVEL_BASIC, USER_LEVEL_MEDIUM, USER_LEVEL_ADVANCED, USER_LEVEL_EXPERT, GENERAL_AVERAGE, GENERAL_INFORMATION, USER_AVERAGE_EQUAL
}
